### ISSUE TITLE
MISSING FEATURE

### ISSUE THREAD

**Issue by PantsuPartyy** [RoyRiv3r/SocialMediaLinkConverter.plugin.js#11]
phixiv for pixiv seems to be missing in the settings, so is deviantart. im on version 0.0.8

**Comment by RoyRiv3r** [comment]
Hi, it seems like the problem isn't on my end. Betterdiscord isn't updating automatically when I push the update, I can't do much about it, you'll need to [download](https://github.com/RoyRiv3r/SocialMediaLinkConverter.plugin.js/blob/main/SocialMediaLinkConverter.plugin.js) the latest version from this repository to fix the issue.
