### ISSUE TITLE
the plugin working on editing messages

### ISSUE THREAD

**Issue by huskyon9** [RoyRiv3r/SocialMediaLinkConverter.plugin.js#15]
sometimes the embed links preview not working,
i need to edit the message change back to normal links.
the plugin will help to change embed links in the editing,
it make the message show edited but still in embed links not the normal links.

**Comment by RoyRiv3r** [comment]
Can you provide specific examples of the embed links preview or host not working?
To be clear this plugin has nothing to do with the hosts, if they don't work it means the service has shutdown or temporary unavailable, this plugin just uses them, you can also add your own or someone'else.

**Comment by huskyon9** [comment]
![image](https://github.com/user-attachments/assets/d4a36ff0-b0f1-4fd4-ad76-ec09318ecb99)
if the hosts not working will look like the image show.
i know it's not your plugin problem but i need to change back the link to normal (ddinstagram.com --> instagram.com)
in my case, i need to edit the message from ddinstagram.com to instagram.com, the plugin will force my change ddinstagram.com.
this part may need to split it or disable it.

**Comment by RoyRiv3r** [comment]
You can separately disable each host so it doesn't bother you anymore, or maybe i'm missing something 
![image](https://github.com/user-attachments/assets/92586288-3b82-4c45-97f0-0ab913806796)

**Comment by huskyon9** [comment]
no, i'm talking on message editing, your plugin works fine. you don't get it what i am talking on.
your plugin change the link on **message editing** when i don't need it help to change because the embed hosts offline or some problem.
here is the video i show with my problem
https://github.com/user-attachments/assets/d3905d53-2966-479e-81d2-11bc29886f22

**Comment by RoyRiv3r** [comment]
I see what you mean now, you want to be able to edit message without the conversion
I might add a toggle to disable message editing conversion for the next update.

**Comment by huskyon9** [comment]
thank you so much.
