### ISSUE TITLE
Youtube Links.

### ISSUE THREAD

**Issue by Primus1243** [RoyRiv3r/SocialMediaLinkConverter.plugin.js#19]
This is for the new youtube links with koutu.be option.  First, we have the intended link grabbed from address bar or video 'copy video url' option.
![image](https://github.com/user-attachments/assets/70cd0d1d-748e-43da-8dab-5307c2b19e8d)

Next we have what it does with the convertor.
![image](https://github.com/user-attachments/assets/d02e687f-ddee-4d92-9b00-a00356ab9807)

I don't think this was supposed to happen.

Side note, is it possible to add the option for quality in the yt.cdn.13373333.one option?  As sometimes it would come out blurry and cheap when watching from discord due to full screen effect on mobile or trying to see tiny details when choosing full screen mode.

As there is none here and locks it at either 480p or lower even though you might have fast internet.
![image](https://github.com/user-attachments/assets/a7d472a8-3a31-4e35-922b-ccf61f806977)

**Comment by RoyRiv3r** [comment]
> This is for the new youtube links with koutu.be option. First, we have the intended link grabbed from address bar or video 'copy video url' option. ![image](https://private-user-images.githubusercontent.com/62166949/357927375-70cd0d1d-748e-43da-8dab-5307c2b19e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTA0MDksIm5iZiI6MTcyMzcxMDEwOSwicGF0aCI6Ii82MjE2Njk0OS8zNTc5MjczNzUtNzBjZDBkMWQtNzQ4ZS00M2RhLThkYWItNTMwN2MyYjE5ZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MGI0N2UwNjg4ODFjYzA1MjNkZmQwZmM0MjY4MDU5MTJjZjQxOGUzN2U3ZTRmYTU2YTQ0OGMxNDVlZDNiOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mu32JmfU-yJfJsM7eP7oSTmRvYUy8itPnU0qIcaVIr0)
> 
> Next we have what it does with the convertor. ![image](https://private-user-images.githubusercontent.com/62166949/357927588-d02e687f-ddee-4d92-9b00-a00356ab9807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTA0MDksIm5iZiI6MTcyMzcxMDEwOSwicGF0aCI6Ii82MjE2Njk0OS8zNTc5Mjc1ODgtZDAyZTY4N2YtZGRlZS00ZDkyLTliMDAtYTAwMzU2YWI5ODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTFhMzA1NzkzNzgwYjMxMzc3NzAyNGFlN2M2NDlmOWZiZTUzZDBmMGRlOTUxYzBlYjA0NTZlZjQ3NjRjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ptBFhQWWvogWHFtGLAVR8YKVQCHDGnv16r1xn2Mogc)
> 
> I don't think this was supposed to happen.
> 

This was an issue on the Invidious side https://github.com/iv-org/invidious/issues/4734#issuecomment-2268996911 although it should be fixed by now.
I don't provide the services, the only purpose of this plugin is to use them and auto convert links, nothing else.

> Side note, is it possible to add the option for quality in the yt.cdn.13373333.one option? As sometimes it would come out blurry and cheap when watching from discord due to full screen effect on mobile or trying to see tiny details when choosing full screen mode.
> 
> As there is none here and locks it at either 480p or lower even though you might have fast internet. ![image](https://private-user-images.githubusercontent.com/62166949/357928819-a7d472a8-3a31-4e35-922b-ccf61f806977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTA0MDksIm5iZiI6MTcyMzcxMDEwOSwicGF0aCI6Ii82MjE2Njk0OS8zNTc5Mjg4MTktYTdkNDcyYTgtM2EzMS00ZTM1LTkyMmItY2NmNjFmODA2OTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkM2FkNDYzOTFlNjk1MTc0NjZiMzY0YThhODQ2ZDlmYzk2ZjFkN2VlOWI1YWZkYmIzM2M5NmUzZmZjYzRlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afN7F7699PjqU7zA0SjI1738dnKryApbWaSeyrvpHh0)

If the service doesn't offer it, there's absolutely nothing I can do, sorry.
Try to ask if https://github.com/ray-1337/youtube-discord-embed can add those video quality options
However I saw https://github.com/iGerman00/koutube have the itag for video quality, but doesn't seem to work. I have opened an issue.
