### ISSUE TITLE
Nitter for Twitter

### ISSUE THREAD

**Issue by iiTzRichie** [RoyRiv3r/SocialMediaLinkConverter.plugin.js#20]
Personally I like using [Nitter](https://github.com/zedeus/nitter) for keeping up to date with Twitter without actually having to use Twitter. Nitter links don't have any embedding properties, though. I was wondering if it could be possible to support converting Nitter links into Twitter links.

Note: I'm not asking for the addition of a Nitter host for Twitter link conversions. I'm asking for a separate functionality where when I paste Nitter links into Discord, SocialMediaLinkConverter converts them into a Twitter link (either using fxtwitter or vxtwitter). There have been times where people who don't know what Nitter is don't want to click on Nitter links that I post.

**Comment by RoyRiv3r** [comment]
I thought Nitter had died.
Do you use instance or something for nitter? 
Could you provide an example link, should be easy to add.

If you want to add your own, just edit the plugin on discord or notepad.

example for [https://xcancel.com/retro_twt/status/1826836792768672155#m](https://xcancel.com/retro_twt/status/1826836792768672155#m) edit the following code line 247 like this:


`{
  id: 'Twitter',
  regex: /https:\/\/(twitter\.com|x\.com|xcancel\.com)\/\w+\/status\/\d+/g,
  replacement: 'https://fxtwitter.com/',
},`

we have added the regex pattern `|xcancel\.com`

**Comment by iiTzRichie** [comment]
> I thought Nitter had died. 

It did for the most part, but some instance hosters are dedicated to keeping their instance going.


> Do you use instance or something for nitter? Could you provide an example link, should be easy to add.
>
> If you want to add your own, just edit the plugin on discord or notepad.
> 
> example for https://xcancel.com/retro_twt/status/1826836792768672155#m edit the following code line 247 like this:
> 
> `{ id: 'Twitter', regex: /https:\/\/(twitter\.com|x\.com|xcancel\.com)\/\w+\/status\/\d+/g, replacement: 'https://fxtwitter.com/', },`

Awesome! Thanks! Though me personally I like to use the instance _nitter.poast.org_. How can I go about adding that to the code?

**Comment by RoyRiv3r** [comment]
You just have to escape the dots `|nitter\.poast\.org`.
Like this : 
```
{
    id: 'Twitter',
    regex: /https:\/\/(twitter\.com|x\.com|nitter\.poast\.org)\/\w+\/status\/\d+/g,
    replacement: 'https://fxtwitter.com/',
},
```

This should replace the links for _nitter.poast.org_

**Comment by iiTzRichie** [comment]
> You just have to escape the dots `|nitter\.poast\.org`. Like this :
> 
> ```
> {
>     id: 'Twitter',
>     regex: /https:\/\/(twitter\.com|x\.com|nitter\.poast\.org)\/\w+\/status\/\d+/g,
>     replacement: 'https://fxtwitter.com/',
> },
> ```
> 
> This should replace the links for _nitter.poast.org_

Awesome! Thanks!
